config/routes.rb
Rails.application.routes.draw do
    
  get 'reports/week' => 'reports#week', as: 'week_reports'
  post '/reports/update_all', to: 'reports#update_all', as: 'update_all_reports'
  post '/reports/create_all', to: 'reports#create_all', as: 'create_all_reports'
  post '/reports/approve', to: 'reports#approve', as: 'approve_reports'
  resources :reports
  post "reports/new"
  get '/reports/:project_id/sub_task.json' => 'reports#task_depend', as: 'task_depend', :format => :json
  
  
  resources :one_tasks
  post "one_tasks/new"
  get '/one_tasks/:id/import' => 'one_tasks#import', as: 'import_one_task'
  post '/one_tasks/:id/do_import' => 'one_tasks#do_import', as: 'do_import_one_task'
  post '/one_tasks/:id/update_all', to: 'one_tasks#update_all', as: 'update_all_one_task'
  
  resources :roles
  post "roles/new"
  get '/myroles' => 'roles#myroles', as: 'my_roles'
  post '/roles/new_task' => 'roles#new_task', as: 'new_task_role'
  post '/roles/task' => 'roles#create_t_role', as: 'create_task_role'
  get '/dofun/:project_id/sub_user' => 'roles#dofun', as: 'dofun', :format => :json
  get '/proj_depend/:user_id/sub_user.json' => 'roles#proj_depend', as: 'proj_depend', :format => :json
  get '/set_projects_s' => 'roles#set_projects_s', as: 'set_projects_s', :format => :json
  
  
  resources :projects
  post "projects/new"
  
  resources :customers
  post "customers/new"
  
  get '/users' => 'users#index', as: 'users'
  get '/users/:id', to: 'users#show', as: 'user'
  patch '/users/:id', to: 'users#update'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  delete '/users/:id', to: 'clearance/users#destroy'
    
  get 'dashboard/index'
  get 'home/index'
     get 'dashboard/reports'
     post '/dashboard/approve_all', to: 'dashboard#approve_all', as: 'approve_all_dashboard'
     post '/dashboard/verde_approve', to: 'dashboard#verde_approve', as: 'verde_approve_dashboard'
     
  
  root 'home#index'
  
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :customer
  has_many :roles, :dependent => :destroy
  has_many :tasks, :dependent => :destroy
  has_many :users, through: :roles
  has_many :one_tasks, through: :tasks
  has_many :reports, through: :tasks
  
  after_initialize :init, :if => :new_record?
  
  def init
    self.status  ||= true     #will set the default value only if it's nil
  end
  
  validates :customer_id, :presence => true
  validates :name, :length => {:maximum => 50},
                    :presence => true                    
  validates_date :start_at, :allow_blank => true
  validates_date :end_at, :allow_blank => true
  validates :budget, :numericality => { only_decimal: true },
                     :allow_nil => true
                      
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout "main_page"
  before_filter :authorize, :authorize_company
  before_action :authorize_level, only: [:create, :new, :update, :destroy, :delete, :edit]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  
  def authorize_level
    if current_user.level != "VE"
      redirect_to projects_path, :alert => "You are not authorized to perform this action!"
    end
  end
  
  def index
    if params[:stat].nil? || params[:stat] == '1'
      @archive_value = [true, false]
      if current_user.level != "VE"
        @project = managerProjectConstraint().where(status: true)
      else
        @project = Project.where(status: true)
      end
    else 
      @archive_value = [false, true]
      if current_user.level != "VE"
        @project = managerProjectConstraint()
      else
        @project = Project.all
      end
    end
  end
  
  def show
    if current_user.level != "VE"
      @project_all = managerProjectConstraint()
      if (@project_all.include?(@project)) == false
        redirect_to projects_path, :alert => "You are not authorized to perform this action!"
      end
    end  
    @one_tasks = @project.one_tasks.all.order(wbs_code: :asc)
    
    # begin
      # session.delete(session[:return_to_project_show])
    # end 
    session[:return_to_project_show] = project_path(@project)
  end
  
  def edit
    @customers = Customer.all.where(status: true)
  end
  
  def new
    @project = Project.new
    @customers = Customer.all.where(status: true)
  end
  
  def create
    @customers = Customer.all.where(status: true)
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @customers = Customer.all.where(status: true)
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_path(@project), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: customer_path(@project) }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
  
    def set_project
      @project= Project.find(params[:id])
    end
  
    def project_params
      params.require(:project).permit(:name, :info, :start_at, :end_at, :budget, :status, :customer_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def join_tags(project)
    project.customer.map { |t| t.name }
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |project_form| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
      <label id="li_error"><%= message %></label> <br>
      <% end %> <br>
		
    </div>
  <% end %>

  <div class="field">
    <%= project_form.label :name %><br>
    <%= project_form.text_field :name %>
  </div>
  
  <div class="field">
    <%= project_form.label :customer%><label id="select_help"> Choose customer for your project</label><br>  
  	<%= project_form.select :customer_id, options_for_select(@customers.map{ |s| [s.name, s.id] })%>
  </div>
  <div class="field">
    <%= project_form.label :start_at %><br>
    <%= project_form.date_field :start_at %>
  </div>
  <div class="field">
    <%= project_form.label :end_at %><br>
    <%= project_form.date_field :end_at %>
  </div>
  <div class="field">
    <%= project_form.label :budget %><br>
    <%= project_form.text_field :budget %>
  </div>
  <div class="field">
    <%= project_form.label :info %><br>
    <%= project_form.text_area :info %>
  </div>
  <div class="field">
  	<%= project_form.label :status %><br>
  	<%= project_form.label :status, 'Active', :value => "true" %>
  	<%= project_form.radio_button :status, true %>
  	<%= project_form.label :status, 'Archive', :value => "false" %>
  	<%= project_form.radio_button :status, false %>
  </div> 
  
  <p>
  <div class="actions">
    <%= project_form.submit :onclick => "return confirm('Are you sure?')", :class=>"myButton"%>
  </div> </p>
<% end %>

app/views/projects/_project.html.erb
 	<tr id="t_project" class="<%= project.status %>">        
        <td><%= project.name %></td>
        <td><%= project.customer.name %></td>
        <td><%= link_to 'Show', project_path(project) %></td>
        <td></td>
 	</tr>

app/views/projects/edit.html.erb
<% content_for :content do %>
	<h2 class="simple"><%= @project.name %></h2><br>
	<%=render 'form'%>
	
	<%= link_to 'back', project_path(@project) %>
<%end%>

app/views/projects/index.html.erb
<% content_for :content do %>
	<h2 class="simple">projects</h2>

	<% unless flash[:alert].nil? %>
		<div class="alert"><%= flash[:alert] %></div>
	<% end %>
	<% unless flash[:notice].nil? %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>

<p><center>
<%= form_tag("projects", method: "get") do%>
  <%= label_tag(:stat, "Show only:") %><br>
  <%= label_tag(:stat, "Active projects") %>
  <%= radio_button_tag(:stat, 1, @archive_value[0]) %>
  <%= label_tag(:stat, "All projects") %>
  <%= radio_button_tag(:stat, 2, @archive_value[1]) %>
  <%= submit_tag("Refresh", :class=>"myButton") %>
<%end%>
</center></p>

<table align="center" class="TFtable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Customer</th>
      <th>Start at</th>
      <th>End at</th>
      <th>Budget</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @project.each do |project| %>
      <tr id="row" class="<%= project.status %>">        
        <td><%= project.name %></td>
        <td><%= project.customer.name %></td>
        <td><%= project.start_at %></td>
        <td><%= project.end_at %></td>
        <td><%= project.budget %></td>
        <td style="max-width: 14px;"><%= link_to 'Show', project_path(project) %></td>
        <td style="max-width: 9px;"><%= link_to 'Edit', edit_project_path(project) %></td>
        <td style="max-width: 18px;"><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure you want to DELETE this Project?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= button_to 'New Project', new_project_path, :class=>"myButton" %>

<%end%>

app/views/projects/new.html.erb
<% content_for :content do %>
	<h2 class="simple">project</h2><br>
	<%= render 'form' %>
	<%= link_to 'Back', projects_path %>
<%end%>

app/views/projects/show.html.erb
<% content_for :content do %>
	<h2 class="simple"><%= @project.name %></h2><br>
	<% unless flash[:alert].nil? %>
		<div class="alert"><%= flash[:alert] %></div>
	<% end %>
	<% unless flash[:notice].nil? %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>
 
<p>
  <strong>Customer:</strong>
  <%= @project.customer.name %>
</p> 
 
<p>
  <strong>Start at:</strong>
  <%= @project.start_at %>
</p> 
 
<p>
  <strong>End at:</strong>
  <%= @project.end_at %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @project.budget %>
</p>

<p>	
  <strong>Info:</strong>
  <div style="word-wrap: break-word; width: 70%;">
  	<%= @project.info %>
  </div>
</p>

<p>
  <strong>Status:</strong>
  <%= show_status(@project.status) %>
</p>
<br>

<%= link_to 'Edit', edit_project_path(@project) %> <br>
<%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure you want to DELETE this Project?' } %><br>
<%= link_to 'Back', projects_path %>
<hr> <h1 class="simple">tasks</h1><br>

<table id="t_import" align="center" class="TFtable" style="display: block; overflow: auto; font-size: 13; font-family: 'Arial' ">
  <thead>
    <tr>
      <th>Wbs</th>
      <th>Name</th>
      <th>Supply</th>
      <th>Work(h)</th>
      <th>Start</th>
      <th>End</th>
      <th>Dur.(d)</th>
      <th>Priority</th>
      <th>state</th>
      <th>SV</th>
      <th>SPI</th>
      <th>Owner</th>
      <th>Src type</th>
      <th>Type</th>
      <th>Assign.</th>
      <th colspan="15"></th>
    </tr>
  </thead>

  <tbody style="font-size: 11; font-family: 'Arial'">
    <% @one_tasks.each do |one_task| %>
    	
      <tr> 
      	<td align="right"><%= one_task.wbs_code %></td>
        <td style="padding-left: <%= (one_task.wbs_code.split(".").size - 1) * 20 %>px;"> <FONT style="BACKGROUND-COLOR: #8FD0FF;"><%= one_task[:task_name]%></FONT> </td>
        <td><%= one_task[:supply_name]%></td>
        <td><%= one_task[:work]%></td>
        <td><%= one_task[:start_at].strftime("%d-%m-%Y")%></td>
        <td><%= one_task[:end_at].strftime("%d-%m-%Y")%></td>
        <td><%= one_task[:duration_day]%></td>
        <td><%= one_task[:priority]%></td>
        <td><%= one_task[:state]%></td>
        <td><%= one_task[:sv]%></td>
        <td><%= one_task[:spi]%></td>
        <td><%= one_task[:owner_assign]%></td>
        <td><%= one_task[:source_type]%></td>
        <td><%= one_task[:type_t]%></td>
        <td><%= one_task[:assignment]%></td>
        <!-- <div style="color: red; font"> -->
        <td style="font-size: 16;"><%= link_to '&Xi;'.html_safe, one_task_path(one_task), {:class => 'import_link_to'} %></td>
        <td style="font-size: 16;"><%= link_to '&#9998;'.html_safe, edit_one_task_path(one_task), {:class => 'import_link_to'}%></td>
        <td style="font-size: 16;"><%= link_to '&#10006;'.html_safe, one_task, :class => 'import_link_to' ,method: :delete, data: { confirm: 'Are you sure you want to DELETE this Project?' }  %></td>
        <!-- </div> -->
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= button_to 'Import tasks', import_one_task_path(@project.id), :method => :get, :class=>"myButton" %>
<hr><h1 class="simple">milestones</h1><br>
<table id="t_import" align="center" class="TFtable" style="display: block; overflow: auto; font-family: 'Arial'">
  <thead style="">
    <tr>
      <th>Name</th>
      <th>Work(h)</th>
      <th>Start</th>
      <th>End</th>
      <th>Duration(d)</th>
      <th>Priority</th>
      <th>state</th>
      <th>Owner</th>
      <th colspan="9">Type</th>
    </tr>
  </thead>

  <tbody style="font-size: 13;">
    <% @one_tasks_milestone = @one_tasks.where(milestone: true) %>
    <% @one_tasks_milestone.each do |one_task_m| %>
      <tr> 
        <td><%= one_task_m[:task_name]%></td>      <!-- style="padding-left: 20px;" -->
        <td><%= one_task_m[:work]%></td>
        <td><%= one_task_m[:start_at]%></td>
        <td><%= one_task_m[:end_at]%></td>
        <td><%= one_task_m[:duration_day]%></td>
        <td><%= one_task_m[:priority]%></td>
        <td><%= one_task_m[:state]%></td>
        <td><%= one_task_m[:owner_assign]%></td>
        <td><%= one_task_m[:type_t]%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%end%>