config/routes.rb
Rails.application.routes.draw do
    
  get 'reports/week' => 'reports#week', as: 'week_reports'
  post '/reports/update_all', to: 'reports#update_all', as: 'update_all_reports'
  post '/reports/create_all', to: 'reports#create_all', as: 'create_all_reports'
  post '/reports/approve', to: 'reports#approve', as: 'approve_reports'
  resources :reports
  post "reports/new"
  get '/reports/:project_id/sub_task.json' => 'reports#task_depend', as: 'task_depend', :format => :json
  
  
  resources :one_tasks
  post "one_tasks/new"
  get '/one_tasks/:id/import' => 'one_tasks#import', as: 'import_one_task'
  post '/one_tasks/:id/do_import' => 'one_tasks#do_import', as: 'do_import_one_task'
  post '/one_tasks/:id/update_all', to: 'one_tasks#update_all', as: 'update_all_one_task'
  
  resources :roles
  post "roles/new"
  get '/myroles' => 'roles#myroles', as: 'my_roles'
  post '/roles/new_task' => 'roles#new_task', as: 'new_task_role'
  post '/roles/task' => 'roles#create_t_role', as: 'create_task_role'
  get '/dofun/:project_id/sub_user' => 'roles#dofun', as: 'dofun', :format => :json
  get '/proj_depend/:user_id/sub_user.json' => 'roles#proj_depend', as: 'proj_depend', :format => :json
  get '/set_projects_s' => 'roles#set_projects_s', as: 'set_projects_s', :format => :json
  
  
  resources :projects
  post "projects/new"
  
  resources :customers
  post "customers/new"
  
  get '/users' => 'users#index', as: 'users'
  get '/users/:id', to: 'users#show', as: 'user'
  patch '/users/:id', to: 'users#update'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  delete '/users/:id', to: 'clearance/users#destroy'
    
  get 'dashboard/index'
  get 'home/index'
     get 'dashboard/reports'
     post '/dashboard/approve_all', to: 'dashboard#approve_all', as: 'approve_all_dashboard'
     post '/dashboard/verde_approve', to: 'dashboard#verde_approve', as: 'verde_approve_dashboard'
     
  
  root 'home#index'
  
  

end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :task
  has_one :one_task, through: :task
   
  validates :user_id, :presence => true,
                     :allow_blank => false
  validates :project_id, :presence => true,
                     :allow_blank => false

  validates :special, :length => {:maximum => 20}  
  validates :r_name, :presence => true
  validates_date :start_at, :allow_blank => true
  validates_date :end_at, :allow_blank => true
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  layout "main_page"
  before_filter :authorize, :authorize_company
  before_action :authorize_level, only: [:show, :create, :new, :new_task, :create_t_role, :update, :destroy, :delete, :edit, :index, :dofun]
  before_action :set_role, only: [:destroy, :edit, :update]
  before_action :set_projects, only: [:new, :create, :edit, :new_task, :create_t_role, :dofun, :proj_depend]
  before_action :set_users, only: [:new, :create, :edit, :new_task, :create_t_role]
  before_action :set_tasks, only: [:new_task, :create_t_role]
  
  def authorize_level
    if current_user.level != "VE" && current_user.level != "PM"
      redirect_to my_roles_path(@roles), :alert => "You are not authorized to perform this action!"
    end
  end
  
  def set_projects_s
    @projects_s = Project.find(params[:project_id])
    respond_to do |format|
      format.json { render :json => @projects_s }
      format.js
    end
  end
  
  def index      
    if params[:stat].nil? || params[:stat] == '1'
      if current_user.level == "PM"
        @projects = managerProjectConstraint().where(status: true)
      else
        @projects = Project.where(status: true)
      end
    else 
      if current_user.level == "PM"
        @projects = managerProjectConstraint()
      else
        @projects = Project.all
      end
    end
    
    if ((params[:project_id].nil?) == false) && (params[:project_id].empty? == false)
      @proj = Project.find(params[:project_id])
    else
      if current_user.level == "PM"
        @proj = managerProjectConstraint().where(status: true)
      else 
        @proj = Project.where(status: true)
      end 
    end
  end
  
  def edit
    if current_user.level == "PM" && current_user.roles.where(special: "project_manager").include?(r) == false
      redirect_to roles_path, :alert => "You are not authorized to perform this action!"
    end
  end
  
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to role_path(@role.user_id), notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: role_path(@role.user_id) }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def dofun        
    if (params[:project_id].nil?)== false
      @tasks11 = Project.find(params[:project_id]).one_tasks
      respond_to do |format|
        format.json { render :json => @tasks11 }
      end
    else
      
    end   
  end
  
  def proj_depend
    if (params[:user_id].nil?)== false
      @projects11 = []
      @projec = User.find(params[:user_id]).projects
      @projects.each do |proj|
          if @projec.include?(proj) && proj.one_tasks.any?
            @projects11.push(proj) 
          end
      end
      respond_to do |format|
        format.json { render :json => @projects11 }
      end
    end    
  end
  
  def myroles
    @user = current_user
    @roles = @user.roles.where(task_id: nil)
  end
  
  def show
    @user = User.find(params[:id])
    if current_user.level == "PM"
      @roles = []
      @t = current_user.roles.where(special: "project_manager").order(id: :asc)
      if @t.any? && @user.level != "VE"
        @range = @t.map {|m| m.project_id}
        @roles = @user.roles.where(task_id: nil, project_id: @range)
      end
    else
      @roles = @user.roles.where(task_id: nil)  
    end
  end
  
  def new
    @role = Role.new
  end
  
  def new_task
    @role = Role.new
    @idecko = params[:task_id]
  end
  
  def create
    @check = 0
    @role = Role.new(role_params)
    @role.valid?
    if @role.project_id.nil? == false && @role.user_id.nil? == false
      if Role.where(user_id: @role.user_id, project_id: @role.project_id).any?
        @role.errors.add(:project_id, ": User is already attached to this project")
      end
    end   
    if @role.special.nil? == false && @role.user.nil? == false
      if @role.special == "project_manager" && @role.user.level != "PM"
        @check = 1
      end
    end

    respond_to do |format|
      if @role.errors.any? == false && (@role.project_id.nil?) == false && @check == 0
        if @role.save
          format.html { redirect_to roles_path, notice: 'Role was successfully created.' }
          format.json { render :index, status: :created, location: roles_path }
        else
          format.html { render :new }
          format.json { render json: @role.errors, status: :unprocessable_entity }
        end
      else
        if @check == 1  
          @role.errors.add(:special, ": You can not choose user as project manager, because he does not have level of Project Manager")
        end
        if @role.project_id.nil?
          @role.errors.add(:project_id, ": You must choose project for your role")
        end
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def create_t_role
    @role = Role.new(role_params)
    if @role.task_id
      t_id = OneTask.find(@role.task_id).task.id
      @role.task_id = t_id
    end
    
    respond_to do |format|
      if (@role.task_id.nil?) == false && (@role.project_id.nil?) == false
        if @role.save
          format.html { redirect_to roles_path, notice: 'Task was successfully assigned.' }
          format.json { render :index, status: :created, location: roles_path }
        else
          format.html { render :new_task }
          format.json { render json: @role.errors, status: :unprocessable_entity }
        end
      else
        if @role.task_id.nil?
          @role.errors.add(:task_id, ": You must choose task for your role")
        end
        if @role.project_id.nil?
          @role.errors.add(:project_id, ": You must choose project for your role")
        end
        format.html { render :new_task }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    if current_user.level == "PM"
      if managerProjectConstraint().include?(@role.project) == false
        redirect_to roles_path, :alert => "You are not authorized to perform this action!" and return
      end
    end
    
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_path, notice: 'User was successfully removed from project.' }
      format.json { head :no_content }
    end
  end
  
  private
  
    def get_path
      current_uri = request.env['PATH_INFO']
    end
  
    def set_role
      @role = Role.find(params[:id])
    end
    
    def set_projects
      if current_user.level == "PM"
        @projects = managerProjectConstraint().where(status: true)
      else
        @projects = Project.where(status: true)
      end
    end
    
    def set_tasks      
      if current_user.level == "PM"
        @tasks = []
        @projects.each do |proj|
          if proj.one_tasks
            proj.one_tasks.each do |t|
              if (t.task_name.blank?) == false
                @tasks.push(t) 
              end     
            end
          end
        end
      else
        @tasks = OneTask.joins(project: :tasks).distinct.where("task_name IS NOT NULL")
      end
    end
    
    def set_users
      if current_user.level == "PM"
        @users = User.where("last_name != ''").where(status: true).where("id != ?", current_user.id)
      else
        @users = User.where("last_name != ''").where(status: true)
      end
    end
  
    def role_params
      params.require(:role).permit(:id, :r_name, :start_at, :end_at, :state, :user_id, :project_id, :task_id, :special)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
  def project_and_user(role)
    if role.project_id.nil?
      role.errors.add(:project_id, "You must choose project for your role")
    end
  end
  
  def get_tasks(project1)
    @tasks1 = []
    @tasks.each do |t|
      if t.project.id == project1.id
        @tasks1.push(t)
      end
    end
    if @tasks1
      @tasks1 = @tasks1.sort_by {|ta| ta[:end_at]}
    end
  end
  
  def selected_value(t_id)
    print "GGGGGGGGGGGGGGGGGGf#{t_id}GGGGGGGGGGGGGGGGGGGG"
    print "dsdasdadasdasdasdadsadasdasda"
  end
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |role_form| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
      <label id="li_error"><%= message %></label> <br>
      <% end %> <br>
		
    </div>
  <% end %>
  
	<% unless flash[:alert].nil? %>
		<div class="alert"><%= flash[:alert] %></div>
	<% end %>
	<% unless flash[:notice].nil? %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>  
  
  <div class="field">
    <%= role_form.label :user%><label id="select_help"> Choose user for your role</label><br>  
  	<%= role_form.select :user_id, options_for_select(@users.map{ |s| [s.full_name, s.id] })%>
  </div>
  <div class="field">
    <%= role_form.label :project%><label id="select_help"> Choose project for your role</label><br>  
  	<%= role_form.select :project_id, options_for_select(@projects.map{ |s| [s.name, s.id] })%>
  </div>
  
  <% if current_user.level == "VE" %>
  	<p>
    	<input type="button" onclick="setSpecialRole()" value="as Project manager" , class="myButton"><br>
    	<%= fields_for :object do |timer_form| %>
  			<%= timer_form.text_field  :special , {:id => "special_role_label", :onkeyup => 'setSpecialRole()'}%>
  		<% end %>
    	<%= role_form.hidden_field :special, {:id => "special_role_field", :onkeyup => 'setSpecialRole()'} %>	
    </p> 
  <% end %>	
  
  <div class="field">
    <%= role_form.label :r_name %> 
    
    <br>
    <%= role_form.text_area :r_name %>
  </div>
  <div class="field">
    <%= role_form.label :state %><br>
    <%= role_form.text_area :state %>
  </div>
  <div class="field">
    <%= role_form.label :start_at %><br>
    <%= role_form.date_field :start_at %>
  </div>
  <div class="field">
    <%= role_form.label :end_at %><br>
    <%= role_form.date_field :end_at %>
  </div>
  
  <p>
  <div class="actions">
    <%= role_form.submit :onclick => "return confirm('Are you sure?')", :class=>"myButton"%>
  </div> </p>
<% end %>

app/views/roles/_form_edit.html.erb
<%= form_for(@role) do |role_form| %>

  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
      <label id="li_error"><%= message %></label> <br>
      <% end %> <br>
		
    </div>
  <% end %>
  
	<% unless flash[:alert].nil? %>
		<div class="alert"><%= flash[:alert] %></div>
	<% end %>
	<% unless flash[:notice].nil? %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>  
  
  <div class="field"> 
  	<%= role_form.hidden_field :user_id %>  	
  </div>
   <div class="field">
    <%= role_form.hidden_field :project_id %>	
  </div> 
  <div class="field">
  	<%= role_form.hidden_field :task_id %>
  </div>  
  <div class="field">
  	<%= role_form.hidden_field :special %>
  </div> 
  <div class="field">
    <%= role_form.label :r_name %><br>
    <%= role_form.text_area :r_name %>
  </div>
  <div class="field">
    <%= role_form.label :state %><br>
    <%= role_form.text_area :state %>
  </div>
  <div class="field">
    <%= role_form.label :start_at %><br>
    <%= role_form.date_field :start_at %>
  </div>
  <div class="field">
    <%= role_form.label :end_at %><br>
    <%= role_form.date_field :end_at %>
  </div>
  
  <p>
  <div class="actions">
    <%= role_form.submit :onclick => "return confirm('Are you sure?')", :class=>"myButton"%>
  </div> </p>
  
<% end %>

app/views/roles/_form_task.html.erb
<%= form_for @role, :url => create_task_role_path do |role_form| %>

  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
      <label id="li_error"><%= message %></label> <br>
      <% end %> <br>
		
    </div>
  <% end %>
  
	<% unless flash[:alert].nil? %>
		<div class="alert"><%= flash[:alert] %></div>
	<% end %>
	<% unless flash[:notice].nil? %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>  
  
  <% @match = role_form.object %>
  <% @tasks11 = Array.new %>
  <% @projects11 = Array.new %>
  
  <div class="field">
    <%= role_form.label :user%><label id="select_help"> Choose User for your role</label><br>  
  	<%= role_form.collection_select  :user_id, @users, :id, :full_name, {:include_blank => false, :prompt => "Select User"},{ :id => :user_id } %>  	
  </div>
  
    <div class="field">
    <%= role_form.label :project%><label id="select_help"> Choose Project for your role</label><br>  
    <%= role_form.collection_select  :project_id, @projects11, :id, :name, {:include_blank => false, :prompt => "Select Project"},{ :id => :project_id,
  		"data-option-dependent"    => true,
  		"data-option-observed"     => "user_id",
  		"data-option-url"          => "/proj_depend/:user_id:/sub_user.json",
 		 "data-option-key-method"   => :id,
 		 "data-option-value-method" => :name,
   	} %>	
  </div> 
  
  <div class="field">
    <%= role_form.label :task%><label id="select_help"> Choose Task for your role</label><br>  
  	<%= role_form.collection_select  :task_id, @tasks11, :id, :task_name, {:include_blank => false, :prompt => "Select Task"},{ :id => :one_task_id,
 		"data-option-dependent"    => true,
  		"data-option-observed"     => "project_id",
  		"data-option-url"          => "/dofun/:project_id:/sub_user.json",
  		"data-option-key-method"   => :id,
 		 "data-option-value-method" => :task_name
  	 } %>
  </div>  
  <div class="field">
    <%= role_form.label :r_name , :class => "r_name", :remote => true%><br>
    <%= role_form.text_area :r_name %>
  </div>
  <div class="field">
    <%= role_form.label :state %><br>
    <%= role_form.text_area :state %>
  </div>
  <div class="field">
    <%= role_form.label :start_at %><br>
    <%= role_form.date_field :start_at %>
  </div>
  <div class="field">
    <%= role_form.label :end_at %><br>
    <%= role_form.date_field :end_at %>
  </div>
  
  <p>
  <div class="actions">
    <%= role_form.submit :onclick => "return confirm('Are you sure?')", :class=>"myButton"%>
  </div> </p>
  
<% end %>

app/views/roles/_role_user.html.erb
	<% unless flash[:alert].nil? %>
		<div class="alert"><%= flash[:alert] %></div>
	<% end %>
	<% unless flash[:notice].nil? %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>
	
<table align="center" id="t_special" style="width: 100%;">
  <thead>
    <tr id="t_project_menu">
      <th>Name</th>
      <th>Role</th>
      <th>State</th>
      <th>Start at</th>
      <th>End at</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
  	<%print "FFFFFFFF #{@roles.size} FFFFFFFFFff"%>
    <% @roles.each do |role| %>
    	
      <tr id="t_project" class="<%= role.project.status %>">        
        <td = ""><%= role.project.name %></td>
        <td><%= role.r_name %></td>
        <td><%= role.state %></td>
        <td><%= role.start_at %></td>
        <td><%= role.end_at %></td>
        <td><%= link_to '&Xi;'.html_safe, project_path(role.project), {:class => 'icon'}%></td>
        <% if current_user.level == "VE" || (current_user.level == "PM" && role.user_id != current_user.id && User.find(role.user_id).level != "VE") %>
        	<td><%= link_to '&#9998;'.html_safe, edit_role_path(role), {:class => 'icon'}%></td>
        <%end%>
        <td>
        	<% @roles_tasks = @user.roles.where(project_id: role.project.id).where.not(task_id: nil) %>
        	<% if @roles_tasks.any? %>
        	<table id="t_sub_special" style="width: 100%;">
  				<thead>
    				<tr id="t_subtask_menu">
      					<th>Task</th>
      					<th>Role</th>
      					<th>state</th>
      					<th>Start at</th>
      					<th>End at</th>
      					<th colspan="5"></th>
    				</tr>
  				</thead>

  				<tbody>			  
  				  <% @roles_tasks.each do |r| %>
      				<tr id="t_subtask">        
        				<td><%= r.task.one_task.task_name %></td>
        				<td><%= r.r_name %></td>
        				<td><%= r.state %></td>
        				<td><%= r.start_at %></td>
        				<td><%= r.end_at %></td>
        				<td style="width: 40px;"><%= link_to '&Xi;'.html_safe, one_task_path(r.task.one_task), {:class => 'icon'}%>
        				<% if current_user.level == "VE" || (current_user.level == "PM" && r.user_id != current_user.id && User.find(role.user_id).level != "VE") %>
        						<%= link_to '&#9998;'.html_safe, edit_role_path(r), {:class => 'icon'}%>
        					<% end %>
        				</td>
      				</tr>
				  <% end %>
  				</tbody>
			</table>
			<% end %>
        	
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/roles/_submenu.html.erb
<div id="sub_navigation">
	<ul>
  		<li id="li_submenu"><a id="submenu_item" href="<%=my_roles_path(@roles)%>">My roles</a></li>
  		<li id="li_submenu"><a id="submenu_item" href="<%=roles_path(@roles)%>">Roles</a></li>
	</ul>
</div>

app/views/roles/_table_task.html.erb
<% @tasks = @project.one_tasks.where("task_name IS NOT NULL").order(wbs_code: :asc) %>
<% if @tasks.any? %>
<table id="t_sub_special" align="right" style="width: 100%;">
  				<thead>
    				<tr id="t_subtask_menu">
      					<th>Name</th>
      					<th>Start</th>
      					<th>End</th>
      					<th>Milestone</th>
      					<th>People</th>
      					<th colspan="5"></th>
    				</tr>
  				</thead>

  				<tbody>
  				  
  				  <% @tasks.each do |task| %>
      				<tr id="t_subtask">        
        				<td><%= task.task_name %></td>
        				<td><%= task.start_at %></td>
        				<td><%= task.end_at %></td>
        				<td><%= task.milestone %></td>
        				<td>
        					<% @users = task.users %>
        					<table style="width: 100%;">
        						<tbody>
        							<% @users.each do |user| %>
        							<% @rl = Role.where(user_id: user.id, task_id: task.task.id).limit(1) %>
        							<tr>
        								<% @rl.each do |role| %>
        								<td><%= link_to 'dlt', role, method: :delete, data: { confirm: 'Are you sure you want to Remove this User from this Task?' } %></td>
        								<%end%>
        								<td><%= user.last_name %></td>
        							</tr>
        							<% end %>
        						</tbody>
							</table>        					
        				</td>
        				<td><%= link_to 'Show', one_task_path(task) %></td>
      				</tr>
				  <% end %>
  				</tbody>
			</table>
<% end %>

app/views/roles/edit.html.erb
<% content_for :sub_navigation do %>
	<%= render 'submenu'%>
<%end%>

<% content_for :content do %>
	<h2 class="simple">edit role <%= User.find(@role.user_id).full_name %></h2><br>
	<%= render 'form_edit' %>
	<%= link_to 'Back', role_path(@role.user_id) %>
<%end%>

app/views/roles/index.html.erb
<% content_for :sub_navigation do %>
	<%= render 'submenu'%>
<%end%>

<% content_for :content do %>
	<h2 class="simple">roles</h2>
	<h1 class="simple">users on projects</h1>

	<% unless flash[:alert].nil? %>
		<div class="alert"><%= flash[:alert] %></div>
	<% end %>
	<% unless flash[:notice].nil? %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>

<p><center>
<%= form_tag("roles", method: "get") do%>
  <%= label_tag(:stat, "Show only:") %><br>
  <%= label_tag(:stat, "Active projects") %>
  <%= radio_button_tag(:stat, 1, true) %>
  <%= label_tag(:stat, "All projects") %>
  <%= radio_button_tag(:stat, 2) %>
  <%= submit_tag("Refresh", :class=>"myButton") %>
<%end%>
</center></p>

<table align="center" id="t_special" style="width: 100%;">
  <thead>
    <tr id="t_project_menu">
      <th>Name</th>
      <th>Customer</th>
      <th>Start at</th>
      <th>End at</th>
      <th>Budget</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr id="t_project" class="<%= project.status %>">        
        <td><%= project.name %></td>
        <td><%= project.customer.name %></td>
        <td><%= project.start_at %></td>
        <td><%= project.end_at %></td>
        <td><%= project.budget %></td>
        <td><%= link_to 'Show', project_path(project) %></td>
        <td>
        	<% @usr = project.users.distinct %>
        	<% if @usr.any? %>
        	<table id="t_sub_special" align="right" style="width: 100%;">
  				<thead>
    				<tr id="t_subtask_menu1">
      					<th>Last Name</th>
     					<th>First Name</th>    					
      					<th>Department</th>
      					<th colspan="3"></th>
    				</tr>
  				</thead>
					
  				<tbody>
  				  <% @usr.each do |user| %>
  				  <% @role = Role.joins(:user, :project) %>
  				  <% @role = @role.where(project_id: project.id).limit(1) %>
  				  <% @rr = Role.where(user_id: user.id, project_id: project.id, special: "project_manager") %>
      				<tr id="t_subtask1">        
        				<td><% if @rr.any? %> 
        						<label>&#9733</label>
        					<%end%>
        					<%= user.last_name %></td>
        				<td><%= user.first_name %></td>  
        				<td><%= user.department %></td>
        				<td><%= link_to 'Roles', role_path(user) %></td>
        				<td><%= link_to 'User info', user_path(user) %></td>
        				
        				<% @role.each do |role| %>
        				<td><%= link_to 'Remove', role, method: :delete, data: { confirm: 'Are you sure you want to Remove this User from this Project?' } %></td>
        				<%end%>
        				
      				</tr>
  				  <% end %>
  				</tbody>
			</table>
			<% end %>
        	
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= button_to 'Assign user to Project', new_role_path, :class=>"myButton" %> 

<hr><h1 class="simple">tasks in projects</h1><br>
    
<div id="projects_table" align="center">
	<%= form_tag("roles", method: "get", include_blank: false) do%>
  		  <%= label_tag("Choose Project") %>
  		<%= select_tag( :project_id, options_for_select(@projects.map{ |s| [s.name, s.id] }), {:prompt => "Select Project"})%>
  		<%= submit_tag("Refresh", :class=>"myButton") %>
	<%end%>
	
  <table align="center" id="t_special" style="width: 100%;">
  	<thead>
    	<tr id="t_project_menu">
      		<th>Name</th>
      		<th>Customer</th>
      		<th colspan="2"></th>
    	</tr>
  	</thead>
  	<tbody>
       <% if @proj.respond_to?(:each) %>
			<% @proj.each do |project| %>
			<% @project = project %>
 				<tr id="t_project" class="<%= @project.status %>">        
        			<td><%= @project.name %></td>
        			<td><%= @project.customer.name %></td>
        			<td><%= link_to 'Show', project_path(@project) %></td>
        			<td><%= render "table_task" %></td>
 				</tr>
 			<% end %>
		<%else%>
			<%@project = @proj%>
 			<tr id="t_project" class="<%= @project.status %>">        
        		<td><%= @project.name %></td>
        		<td><%= @project.customer.name %></td>
        		<td><%= link_to 'Show', project_path(@project) %></td>
        		<td><%= render "table_task" %></td>
 			</tr>
 		<% end %>
    </tbody>
  </table>  
  </form>  
</div>

<%= button_to 'Assign user to Task', new_task_role_path, :class=>"myButton" %>
<%end%>

app/views/roles/myroles.html.erb
<% content_for :sub_navigation do %>
	<%= render 'submenu'%>
<%end%>

<% content_for :content do %>
	<h2 class="simple">my roles</h2><br>
	<%= render "role_user" %>
<%end%>

app/views/roles/new.html.erb
<% content_for :sub_navigation do %>
	<%= render 'submenu'%>
<%end%>

<% content_for :content do %>
	<h2 class="simple">new assignment to project</h2><br>
	<%= render 'form' %>
	<%= link_to 'Back', roles_path %>
<%end%>

app/views/roles/new_task.html.erb
<% content_for :sub_navigation do %>
	<%= render 'submenu'%>
<%end%>

<% content_for :content do %>
	<h2 class="simple">new assignment to task</h2><br>
	<%= render 'form_task' %>
	<%= link_to 'Back', roles_path %>
<%end%>

app/views/roles/show.html.erb
<% content_for :sub_navigation do %>
	<%= render 'submenu'%>
<%end%>

<% content_for :content do %>
	<h2 class="simple" style="width: 35%;">roles <%= @user.full_name %></h2><br>
	<%= render "role_user" %>
	<%= link_to 'Back', roles_path %>
<%end%>