config/routes.rb
Rails.application.routes.draw do
    
  get 'reports/week' => 'reports#week', as: 'week_reports'
  post '/reports/update_all', to: 'reports#update_all', as: 'update_all_reports'
  post '/reports/create_all', to: 'reports#create_all', as: 'create_all_reports'
  post '/reports/approve', to: 'reports#approve', as: 'approve_reports'
  resources :reports
  post "reports/new"
  get '/reports/:project_id/sub_task.json' => 'reports#task_depend', as: 'task_depend', :format => :json
  
  
  resources :one_tasks
  post "one_tasks/new"
  get '/one_tasks/:id/import' => 'one_tasks#import', as: 'import_one_task'
  post '/one_tasks/:id/do_import' => 'one_tasks#do_import', as: 'do_import_one_task'
  post '/one_tasks/:id/update_all', to: 'one_tasks#update_all', as: 'update_all_one_task'
  
  resources :roles
  post "roles/new"
  get '/myroles' => 'roles#myroles', as: 'my_roles'
  post '/roles/new_task' => 'roles#new_task', as: 'new_task_role'
  post '/roles/task' => 'roles#create_t_role', as: 'create_task_role'
  get '/dofun/:project_id/sub_user' => 'roles#dofun', as: 'dofun', :format => :json
  get '/proj_depend/:user_id/sub_user.json' => 'roles#proj_depend', as: 'proj_depend', :format => :json
  get '/set_projects_s' => 'roles#set_projects_s', as: 'set_projects_s', :format => :json
  
  
  resources :projects
  post "projects/new"
  
  resources :customers
  post "customers/new"
  
  get '/users' => 'users#index', as: 'users'
  get '/users/:id', to: 'users#show', as: 'user'
  patch '/users/:id', to: 'users#update'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  delete '/users/:id', to: 'clearance/users#destroy'
    
  get 'dashboard/index'
  get 'home/index'
     get 'dashboard/reports'
     post '/dashboard/approve_all', to: 'dashboard#approve_all', as: 'approve_all_dashboard'
     post '/dashboard/verde_approve', to: 'dashboard#verde_approve', as: 'verde_approve_dashboard'
     
  
  root 'home#index'
  
  

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
  has_one :project, through: :task
  
  attr_accessor :hours_id, :minutes_id
  
  validates_date :date,
                  :presence => true
  validates_time :time,
                  :presence => true
  validates :task_id, :presence => true,
                      :allow_blank => false                 
  validates :user_id, :presence => true,
                      :allow_blank => false
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  layout "main_page"
  before_filter :authorize, :authorize_company
  before_action :set_projects, only: [:index, :create, :week, :update_all, :create_all]
  before_action :before_week, only: [:week, :create_all, :update_all]
  before_action :before_index, only: [:index, :create]
  before_action :set_report, only: [:destroy]
  
  def before_week
    @tasks = Array.new
    @report = Report.new
    @reports= []
    @err = []
    @err1 = []
    @params_week = params[:week]
    
    @report1 = Report.new
    @reports1 = []
    5.times do ||
      @reports1.push(Report.new)
    end 
    
    if params[:week].nil? == false
      @reports = []
      @d = Date.new(Date.today.year,1,1)
      @rep = Report.where("user_id = ? AND date >= ?", current_user.id, @d).order(date: :desc)  
      @rep.each do |r|
        if r.date.cweek.to_i == params[:week].to_i && (r.approvement.nil? || r.approvement == 1)
          @reports.push(r)
        end
      end
    else
      @reports = []
      @d = Date.new(Date.today.year,1,1)
      @rep = Report.where("user_id = ? AND date >= ?", current_user.id, @d).order(date: :desc)  
      @rep.each do |r|
        if r.date.cweek.to_i == Date.today.cweek.to_i && (r.approvement.nil? || r.approvement == 1)
          @reports.push(r)
        end
      end
    end
  end
  
  def before_index
    @tasks = Array.new
    @report= Report.new
    @search_option = [false, true, false, false]
    @search_day = Time.now.strftime("%Y-%m-%d")
    @search_week = Date.today.cweek.to_i
    @search_month = Date.today.month
    @search_year = Date.today.year
    @search_from = nil
    @search_to = nil
        
    if params[:option].nil? == false
      @search_option = [false, false, false, false] 
      if params[:option] == '1'
        @search_day = params[:day].to_date
        @reports = Report.where(user_id: current_user.id, date: params[:day].to_date)
        @search_option[0] = true
      end
      if params[:option] == '2'
        @search_week = params[:week].to_i
        @search_option[1] = true
        @reports = []
        @d = Date.new(Date.today.year,1,1)
        @rep = Report.where("user_id = ? AND date >= ?", current_user.id, @d).order(date: :desc)  
        @rep.each do |r|
          if r.date.cweek.to_i == params[:week].to_i
            @reports.push(r)
          end
        end
      end
      if params[:option] == '3'
        @search_month = params[:month].to_i
        @search_year = params[:year].to_i
        @search_option[2] = true
        @reports = Report.where('user_id = ? AND extract(month from date) = ? AND extract(year from date) = ?',current_user.id, params[:month].to_i, params[:year].to_i).order(date: :desc)
      end
      if params[:option] == '4'
        @search_from = params[:from].to_date
        @search_to = params[:to].to_date
        @search_option[3] = true
        @range = (params[:from].to_date..params[:to].to_date)
        @reports = Report.where(user_id: current_user.id, date: @range).order(date: :desc)
      end
    else
      @d = Date.today
      @reports = Report.where('user_id = ? AND extract(month from date) = ? AND extract(year from date) = ?',current_user.id, @d.month.to_i, @d.year.to_i).order(date: :desc)
    end
    if @reports.nil?
      @reports = []
    end
    
    hours = @reports.any? ? @reports.map {|m| m.time.hour}.sum : 0
    minutes = @reports.any? ? @reports.map {|m| m.time.min}.sum : 0
    @sum = @reports.any? ? toClock(hours, minutes) : 0
  end
  
  def index
    # gon, for sending variables to js
    
    # @s_time1 = new
    # @s_time2 = new
    # @s_time3 = new
    # @s_time4 = new
    #     
    # gon.s_time = @s_time
    # gon.s_time1 = @s_time1
    # gon.s_time2 = @s_time2
    # gon.s_time3 = @s_time3
    # gon.s_time4 = @s_time4
    # gon.all_variables
  end
  
  def week
  end
  
  def new
    @report= Report.new
  end
  
  def approve
    if params[:format].nil? == false && params[:format].blank? == false
      params[:format].split("/").each do |id|
        @r = Report.find(id.to_i)
        # if @r.approvement.nil? == false
          # redirect_to week_reports_path, :alert => "You have already apprroved Report Week!" and return
        # end
        if @r.user_id != current_user.id
          redirect_to week_reports_path, :alert => "You are not authorized to perform this action!" and return
        end
      end
      params[:format].split("/").each do |id|
        @report = Report.find(id.to_i)
        if @report.update_attributes(:approvement => 1)
        else
          redirect_to week_reports_path, :alert => "There has been errors during apprrove Report Week." and return
        end
      end
    end 
    redirect_to reports_path, :notice => "Report Week has been successfully approved." and return
  end
  
  def create
    @report= Report.new(report_params)

    if params[:hours_id] == "02" && params[:minutes_id] == "00"
      if params[:object][:dur].blank? == false 
        @report.time = Time.strptime(params[:object][:dur], "%T") + 2.hours
        @report.time = @report.time - @report.time.sec
      end
    elsif params[:hours_id].nil? == false && params[:minutes_id].nil? == false
      t = params[:hours_id] + ":" + params[:minutes_id] + ":" +  "00"
      @report.time = Time.strptime(params[:hours_id] + ":" + params[:minutes_id] + ":" +  "00", "%T")
    end
    
    @report.user_id = current_user.id
    if @report.task_id
      @report.task_id = OneTask.find(@report.task_id).task.id
    end
    
    @report.valid?
    respond_to do |format|
      if @report.errors.any? == false && @report.save
        format.html { redirect_to reports_path, notice: 'Report was successfully created.' }
        format.json { render :index, status: :created, location: reports_path }
      else
        format.html { render :index }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def create_all
    @err = []
    @reports1 = []
    @id = current_user.id
    rs = params[:reports1]
    @i = 0
    rs.each do |val|
      if val[:task_id].nil? == false && val[:task_id].blank? == false
        @i += 1
        task = OneTask.find(val[:task_id].to_i).task.id
        if val[:hours_id].nil? == false && val[:minutes_id].nil? == false
          time = Time.strptime(val[:hours_id] + ":" + val[:minutes_id] + ":" +  "00", "%T") + 2.hours
        end
        @report1 = Report.new(user_id: @id, date: val[:date], time: time, info: val[:info], task_id: task)
        @reports1.push(@report1)
        @report1.valid?
        if @report1.user_id.nil?
          @report1.errors.add(:user_id, ": You must choose user")
        end
        if @report1.errors.any?
          @err.push(@i.to_s+". line")
          @report1.errors.full_messages.each do |message|
            @err.push(message)
          end
        end
      end   
    end 
    
    respond_to do |format|
      if @err.any? == false
        @reports1.each do |rpt|
          if rpt.save 
          else
            format.html { render :week }
            format.json { render json: @err, status: :unprocessable_entity }
          end
        end
        format.html { redirect_to reports_path, notice: 'Reports were successfully created.' }
        format.json { render :index, status: :created, location: reports_path }
      else
        format.html { render :week }
        format.json { render json: @err, status: :unprocessable_entity }
      end      
    end
  end
  
  def update_all
    @err1 = []
    @reports = []
    @id = current_user.id
    rs = params[:reports]
    @i = 0
    rs.each do |rpt, val|
      @i += 1
      if val[:task_id].nil? || val[:task_id].blank?
        @t_id = val[:helper]
      else
        @t_id = val[:task_id]
      end 
      task = OneTask.find(@t_id.to_i).task.id
      if val[:hours_id].nil? == false && val[:minutes_id].nil? == false
        time = Time.strptime(val[:hours_id] + ":" + val[:minutes_id] + ":" +  "00", "%T") + 2.hours
      end
      @report = Report.new(id: rpt ,user_id: @id, date: val[:date], time: time, info: val[:info], task_id: task,
                           created_at: Report.find(rpt).created_at, updated_at: Time.now)
      if @report.time?
        if @report.time.hour >= 12
          @report.time = @report.time - 12.hours
        end
      end
      @reports.push(@report)
      @report.valid?
      if @report.task_id.nil?
        @report.errors.add(:task_id, ": You must choose task")
      end
      if @report.user_id.nil?
        @report.errors.add(:user_id, ": You must choose user")
      end
      if @report.errors.any?
        @err1.push(@i.to_s+". line")
        @report.errors.full_messages.each do |message|
          @err1.push(message)
        end
      end
    end
      
    respond_to do |format|
      if @err1.any? == false
        @reports.each do |rpt|
          @rep = Report.find(rpt.id)
          if @rep.update(rpt.attributes) 
          else
            format.html { render :week }
            format.json { render json: @err1, status: :unprocessable_entity }
          end
        end
        format.html { redirect_to reports_path, notice: 'Reports were successfully updated.' }
        format.json { render :index, status: :created, location: reports_path }
      else
        format.html { render :week }
        format.json { render json: @err1, status: :unprocessable_entity }
      end      
    end
  end
       
  def task_depend
    if params[:project_id]
      @tasks = Project.find(params[:project_id]).one_tasks
    end 
    respond_to do |format|
      format.json { render :json => @tasks }
    end
  end
  
  def destroy
    if (@report.approvement.nil? == false && @report.approvement != 1) || @report.user_id != current_user.id
      redirect_to reports_path, alert: 'Report was already approved by PM or Verde, or you are trying to delete foreign report.'
    end
    
    @report.destroy
    respond_to do |format|

app/helpers/reports_helper.rb
module ReportsHelper
  def getWeeks()
    @p = Date.new(Date.today.year,12,31)
    @p.strftime("%W").to_i
  end
  
  def getId_s()
    @id_s = []
    @reports.each do |report|
      @id_s.push(report.id)
    end
    return @id_s
  end
  
  def selectedTask(report)
    if report.user_id? == false
      @blank = "Select Task"
      @selected = nil
    else
      @blank = report.task.one_task.task_name
      @selected = report.task.one_task.id
    end
  end
  
  def selectedProject(report)
    if report.user_id? == false
      @prompt = "Select Project"
    else
      @prompt = report.project.name
    end
  end
  
  def getSelectedWeek()
    if @params_week.nil?
      @params_week = Date.today.cweek.to_i
    end
  end
  
  def selectedTime(report)
    report.time? ? @selected_time = (report.time.strftime("%H:%M:%S")).to_time : @selected_time = nil
  end
end

app/views/reports/_form.html.erb
<%= form_for(@report, url: {action: "create"}) do |report_form| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
      <label id="li_error"><%= message %></label> <br>
      <% end %> <br>
		
    </div>
  <% end %>
  
  <div style="background-color: #B6FFEA; height: 109px; padding-top: 0px; border: 1px solid #D0D0D0;">
  <table align="center">
  <thead>
    <tr>
      <th>Project</th>
      <th>Task</th>
      <th>Date</th>
      <th>Duration</th>
      <th></th>
      <th></th>
      <th>
      		<%= fields_for :object do |timer_form| %>
  				<%= timer_form.text_field  :timer , {:id => "timer_start1", :onkeyup => 'startTime()', :size => 5, :style=>"width: auto;"}%>
  			<% end %>
      </th>
      <th>
      		<%= fields_for :object do |timer_form| %>
  				<%= timer_form.text_field  :dur , {:id => "timer_dur", :onkeyup => 'endTime()', :size => 5, :style=>"width: auto;"}%>
  			<% end %>
      </th>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
      <tr>        
        <td>        	
        	<%= fields_for :project do |project_form| %>
  				<%= project_form.collection_select  :project_id, @projects, :id, :name, {:include_blank => false, :prompt => "Select Project"},{ :id => :project_id, :style=>"width: 150px;" } %>
  			<% end %>	 	
        </td>
        <td>
        	<% @tasks = Array.new %>
    		<%= report_form.collection_select  :task_id, @tasks, :id, :task_name, {:include_blank => false, :prompt => "Select Task"},{ :id => :task_id, :style=>"width: 180px;",
  				"data-option-dependent"    => true,
  				"data-option-observed"     => "project_id",
  				"data-option-url"          => "/reports/:project_id:/sub_task.json",
 		 		"data-option-key-method"   => :id,
 		 		"data-option-value-method" => :task_name,} %>
        </td>
        <td>
   			<%= report_form.date_field :date ,{:value => Time.now.strftime("%Y-%m-%d"), :style=>"width: 142px;"}%>
        </td>
        <td>
    		<select name="hours_id" id="hours_id" style="width: auto;">
  				<option value="02">00</option>
  				<option value="03">01</option>
  				<option value="04">02</option>
  				<option value="05">03</option>
  				<option value="06">04</option>
  				<option value="07">05</option>
  				<option value="08">06</option>
  				<option value="09">07</option>
  				<option value="10">08</option>
  				<option value="11">09</option>
  				<option value="12">10</option>
  				<option value="13">11</option>
  				<option value="14">12</option>
			</select>
			<select name="minutes_id" id="minutes_id" style="width: auto;">
  				<option value="00">00</option>
  				<option value="30">30</option>
			</select>
        </td>
        <td>
        	<%= report_form.submit :onclick => "return confirm('Are you sure?')", :class=>"myButton"%>
        </td>
        <td style="padding-left: 80px;"></td>
        <td>
        	<input type="button" onclick="startTime()" value="Start" class="myButton">
        </td>
        <td>
        	<input type="button" onclick="endTime()" value="Stop"  class="myButton">
        </td>
      </tr>
  </tbody>
</table>
	<div style="padding-left: 7px;">
		<%= report_form.text_area :info , {:rows=>"1", :cols=>"42"}%>
	</div>
</div>
  
<% end %>

app/views/reports/_newmany_form.html.erb
<%= form_for @report1, :url => create_all_reports_path do |report_form|%>
  	<% @pom1 = 0 %> 
    	
    		<% if @err.any? %>
				<div id="error_explanation">
    			<h2>Errors prohibited this reports from being saved:</h2>
    			<ul>
    			<% @err.each do |message| %>
    				<% if (message.split(" ").last) == "line" %>
    					<label><%= message %></label> <br>
    				<% else %>
    					<label id="li_error"><%= message %></label> <br>
    				<% end %>
    			<% end %> <br>		
    			</div>
			<% end %>  
  	  
  			<% unless flash[:alert].nil? %>
				<div class="alert"><%= flash[:alert] %></div>
			<% end %>
			<% unless flash[:notice].nil? %>
				<div class="notice"><%= flash[:notice] %></div>
			<% end %>

    <table align="center" style="width: 100%; border-spacing: 0px 0px;">
  		<thead>
    		<tr>
    			<th></th>
      			<th>Project</th>
      			<th>Task</th>
      			<th>Date</th>
      			<th>Duration</th>
      			<th>Info</th>
  		      	<th colspan="6"></th>
    		</tr>
  		</thead>
  		<tbody>
      		
      		
      		<% @reports1.each do |report| %> 
    			<%= fields_for "reports1[]", report do |r_form| %>
      		
      			<% @pom1 += 1 %> 
      			<% @project_id = "project_idd"+@pom1.to_s %>
      			<% @task_id = "task_idd"+@pom1.to_s %>
      		<tr style="background: #E9E9E9;">
      			<td><%= @pom1 %></td>        
        		<td>
        			<% selectedProject(report) %>
        			<%= fields_for :project do |project_form| %>
  					<%= project_form.collection_select  :project_id, @projects, :id, :name, {:include_blank => false, :prompt => @prompt},{ :id => @project_id, :style=>"width: 150px;" } %>
  					<% end %>	
        		</td>
        		<td>
        			<% selectedTask(report) %>
        			<% @tasks = Array.new %>
    				<%= r_form.collection_select  :task_id, @tasks, :id, :task_name, {:include_blank => @blank, :prompt => "Select Task", :selected => @selected},{ :id => @task_id, :style=>"width: 200px;",
  						"data-option-dependent"    => true,
  						"data-option-observed"     => @project_id,
  						"data-option-url"          => "/reports/:"+ @project_id +":/sub_task.json",
 		 				"data-option-key-method"   => :id,
 		 				"data-option-value-method" => :task_name,} %>
        		</td>
        		<td>
        			<%= r_form.date_field :date ,{:style=>"width: 142px;"}%>	
        		</td>
        		<td>
        			<%= r_form.select :hours_id, options_for_select(0..12), {}, {:style=>"width: auto;"}%> 
        			<%= r_form.select :minutes_id, options_for_select([0, 15, 30, 45]), {}, {:style=>"width: auto;"}%> 
        		</td>
        		<td>
        			<%= r_form.text_area :info , {:rows=>"1", :cols=>"38"}%>
        		</td>
  		    </tr>
	

		<%end%>
	<%end%>
	  		</tbody>
  	</table>
	
	<%= report_form.submit "Create Reports", :onclick => "return confirm('Are you sure?')", :class=>"myButton"%>
<%end%>

app/views/reports/_submenu.html.erb
<div id="sub_navigation">
	<ul>
  		<li id="li_submenu"><a id="submenu_item" href="<%=reports_path(@reports)%>">My timesheet</a></li>
  		<li id="li_submenu"><a id="submenu_item" href="<%= week_reports_path %>">My week</a></li>
	</ul>
</div>

app/views/reports/_table_myreport_form.html.erb
<%= form_tag("reports", method: "get") do%>

<div style="background-color: #B6F6FF; height: 68px; padding-top: 5px; border: 1px solid #D0D0D0; border-bottom: 0px;">
  	<div>
  	<table align="left" style="border-spacing: 18px 0px; background-color: #B6F6FF;">
  		<thead>
    		<tr>
    			<th></th>
      			<th>Day</th>
      			<th>Week</th>
      			<th>Month &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Year</th>
      			<th colspan="4">From &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp To</th>
    		</tr>
  		</thead>
  		<tbody>
      		<tr>
      			<td style="width: 50px;" align="left"><%= submit_tag("Refresh", :class=>"myButton") %></td>
        		<td>
        			<%= radio_button_tag(:option, 1, @search_option[0]) %> 
					<%= date_field_tag :day ,value = @search_day, :style=>"width: 142px;" %>	
        		</td>
        		<td>
        			<% @p = getWeeks() %>
					<%= radio_button_tag(:option, 2, @search_option[1]) %> 
					<%= select_tag :week, options_for_select(1..@p, @search_week), :style=>"width: auto;"%> 
        		</td>
        		<td>
        			<%= radio_button_tag(:option, 3, @search_option[2]) %> 
  					<%= select_tag :month, options_for_select((1..12).map {|m| [Date::MONTHNAMES[m], m]}, @search_month), :style=>"width: auto;"%>
  					<%= select_tag :year, options_for_select(2008..Date.today.year, @search_year), :style=>"width: 70px;" %> 
        		</td>
        		<td>
        			<%= radio_button_tag(:option, 4, @search_option[3]) %> 
					<%= date_field_tag :from, @search_from, :style=>"width: 142px;" %>	
					<%= date_field_tag :to, @search_to, :style=>"width: 142px;"%>
        		</td>
  		    </tr>
  		</tbody>
  	</table>
  	</div>
  	
  	
</div>
<div align="center" style="background-color: #EEFFFF; margin-top: 0px; padding-top: 0px; border: 1px solid #D0D0D0; border-top: 0px;">
  		<label style="color: #EEDDFF; border: 1px solid #D0D0D0;">&#9608</label> <label style="font-size: 14">Approved by user (1. level)&nbsp&nbsp&nbsp</label>
		<label style="color: #C9F9FF; border: 1px solid #D0D0D0;">&#9608</label> <label style="font-size: 14">Approved by p.manager/Verde (2. level)&nbsp&nbsp&nbsp</label>
		<label style="color: #A9FFCE; border: 1px solid #D0D0D0;">&#9608</label> <label style="font-size: 14">Approved by Verde (3. level)</label>
	</div>
<%end%>

app/views/reports/_week_form.html.erb
<%= form_for @report, :url => update_all_reports_path do |report_form|%>
  	<% @pom = 0 %> 
    	
    		<% if @err1.any? %>
				<div id="error_explanation">
    			<h2>Errors prohibited this reports from being updated:</h2>
    			<ul>
    			<% @err1.each do |message| %>
    				<% if (message.split(" ").last) == "line" %>
    					<label><%= message %></label> <br>
    				<% else %>
    					<label id="li_error"><%= message %></label> <br>
    				<% end %>
    			<% end %> <br>		
    			</div>
			<% end %>  
  	  
  	<% unless flash[:alert].nil? %>
		<div class="alert"><%= flash[:alert] %></div>
	<% end %>
	<% unless flash[:notice].nil? %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>
    	
    <table align="center" style="width: 100%; border-spacing: 0px 3px;">
  		<thead>
    		<tr>
    			<th></th>
      			<th>Project</th>
      			<th>Task</th>
      			<th>Date</th>
      			<th>Duration</th>
      			<th>Info</th>
  		      	<th colspan="6"></th>
    		</tr>
  		</thead>
  		<tbody>
      		<% @check = 0 %>	
      		<% @reports.each do |report| %> 
    			<%= fields_for "reports[]", report do |r_form| %>
      		
      			<% if (report.approvement.nil? || report.approvement == 1)%>
      				<% @check = 1 %>
      			<%end%>
      			<% @project_id = "project_id"+report.id.to_s %>
      			<% @pom += 1 %> 
      			<% @task_id = "task_id"+@pom.to_s %>
      		<tr id='report_tr' class="color<%= report.approvement %>" style="background: #FCD0D3;">       
      			<td><%= @pom %></td> 
        		<td>
        			<%= fields_for :project do |project_form| %>
  					<%= project_form.collection_select  :project_id, @projects, :id, :name, {:include_blank => false, :prompt => "Select Project", :selected => report.project.id},{ :id => @project_id, :style=>"width: 150px;" } %>
  					<% end %>	
        		</td>
        		<td>
        			
        			<% @tasks = Array.new %>
    				<%= r_form.collection_select  :task_id, @tasks, :id, :task_name, {:include_blank => report.task.one_task.task_name, :prompt => "Select Task", :selected => report.task.one_task.id},{ :id => @task_id, :style=>"width: 200px;",
  						"data-option-dependent"    => true,
  						"data-option-observed"     => @project_id,
  						"data-option-url"          => "/reports/:"+ @project_id +":/sub_task.json",
 		 				"data-option-key-method"   => :id,
 		 				"data-option-value-method" => :task_name,} %>
        		</td>
        		<td>
        			<%= r_form.date_field :date ,{:style=>"width: 142px;"}%>		
        		</td>
        		<td>
        			<% selectedTime(report) %>
        			<%= r_form.select :hours_id, options_for_select(0..12, @selected_time.hour), {}, {:style=>"width: auto;"} %> 
        			<%= r_form.select :minutes_id, options_for_select(0..59, @selected_time.min), {}, {:style=>"width: auto;"}%> 
        		</td>
        		<td>
        			<%= r_form.text_area :info , {:rows=>"1", :cols=>"40"}%>
        		</td>
        		<td>
        			<%= r_form.text_field :helper, :value => report.task.one_task.id, :style=>"visibility: hidden; width: 0px;"%>
        		</td>
  		    </tr>
	

		<%end%>
	<%end%>
	  		</tbody>
  	</table>
	<% if @check == 1 %>
		<%= report_form.submit "Update Reports", :onclick => "return confirm('Are you sure?')", :class=>"myButton"%>
	<%end%>	
<%end%>
<% if @check == 1 %>
	<%= button_to 'Approve Week', approve_reports_path(getId_s()), :method => :post, :class=>"myButton" %>
<%end%>	

app/views/reports/new.html.erb
<%= render 'form' %>

app/views/reports/week.html.erb
<% content_for :sub_navigation do %>
	<%= render 'submenu'%>
<%end%>

<% content_for :content do %>
	<h2 class="simple">week</h2>
	<h1 class="simple">update</h1><br>
	<% unless flash[:alert].nil? %>
		<div class="alert"><%= flash[:alert] %></div>
	<% end %>
	<% unless flash[:notice].nil? %>
		<div class="notice"><%= flash[:notice] %></div>
	<% end %>
 
	<%= form_tag("week", method: "get") do%>
	
		<% @p = getWeeks() %>
		<% getSelectedWeek() %>
		<label>Choose Week</label> <%= select_tag :week, options_for_select(1..@p, @params_week), :style=>"width: auto;"%>

  		<%= submit_tag("Refresh", :class=>"myButton") %>
  	<% end %>
  	
  	<%= render "week_form" %>
  	<hr> <h1 class="simple">create</h1><br>
  	<%= render "newmany_form" %>
<% end %>