config/routes.rb
Rails.application.routes.draw do
    
  get 'reports/week' => 'reports#week', as: 'week_reports'
  post '/reports/update_all', to: 'reports#update_all', as: 'update_all_reports'
  post '/reports/create_all', to: 'reports#create_all', as: 'create_all_reports'
  post '/reports/approve', to: 'reports#approve', as: 'approve_reports'
  resources :reports
  post "reports/new"
  get '/reports/:project_id/sub_task.json' => 'reports#task_depend', as: 'task_depend', :format => :json
  
  
  resources :one_tasks
  post "one_tasks/new"
  get '/one_tasks/:id/import' => 'one_tasks#import', as: 'import_one_task'
  post '/one_tasks/:id/do_import' => 'one_tasks#do_import', as: 'do_import_one_task'
  post '/one_tasks/:id/update_all', to: 'one_tasks#update_all', as: 'update_all_one_task'
  
  resources :roles
  post "roles/new"
  get '/myroles' => 'roles#myroles', as: 'my_roles'
  post '/roles/new_task' => 'roles#new_task', as: 'new_task_role'
  post '/roles/task' => 'roles#create_t_role', as: 'create_task_role'
  get '/dofun/:project_id/sub_user' => 'roles#dofun', as: 'dofun', :format => :json
  get '/proj_depend/:user_id/sub_user.json' => 'roles#proj_depend', as: 'proj_depend', :format => :json
  get '/set_projects_s' => 'roles#set_projects_s', as: 'set_projects_s', :format => :json
  
  
  resources :projects
  post "projects/new"
  
  resources :customers
  post "customers/new"
  
  get '/users' => 'users#index', as: 'users'
  get '/users/:id', to: 'users#show', as: 'user'
  patch '/users/:id', to: 'users#update'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  delete '/users/:id', to: 'clearance/users#destroy'
    
  get 'dashboard/index'
  get 'home/index'
     get 'dashboard/reports'
     post '/dashboard/approve_all', to: 'dashboard#approve_all', as: 'approve_all_dashboard'
     post '/dashboard/verde_approve', to: 'dashboard#verde_approve', as: 'verde_approve_dashboard'
     
  
  root 'home#index'
  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'reports' %>
  <%= stylesheet_link_tag 'blocks' %>
  <%= stylesheet_link_tag 'items' %>
  <%= stylesheet_link_tag 'menu' %>
  <%= stylesheet_link_tag 'basic_graphic' %> 
  <%= csrf_meta_tag %>
  
  <%= include_gon %>
  
</head>
<body style="background: #dadada; min-height: 95%">
	
	<script type="text/javascript">
				var time, result;
				
				function startTime() {
						time = new Date().getTime();
						timer_dur.value = "";
    					timer_start1.value = getTime1(1);
    			}
    					
    			function endTime() {
    					 var time2 = new Date().getTime();
    					 var t3 = time2 - time;
    					 timer_dur.value = getTime1(t3);
						}
						
				function getTime1(n) {
					if (n == 1) { var now = new Date(); }
					else { var now = new Date(n); }
    
    				return ((now.getHours()-1)     + ':' +
             			((now.getMinutes() < 10)
                 		? ("0" + now.getMinutes())
                 		: (now.getMinutes())) + ':' +
             			((now.getSeconds() < 10)
                 		? ("0" + now.getSeconds())
                 		: (now.getSeconds())));
					}
				
				function setSpecialRole() {
					special_role_label.value = "User is set as a Project Manager";
					special_role_field.value = "project_manager";
				}
	</script>

  <%= yield %>
  
</body>
</html>

app/views/layouts/login.html.erb
<div id="login_wrapper">

  <div id="login_box_wrap">
    <div id="login_box">
        <h2 class="simple" style="width: 50%;">Verde s.r.o. LOGIN</h2> 
         <hr id="hr_strong"><br>
        <%= yield :log_content %>
    </div>
  </div>

</div>

 <%= render template: "layouts/application" %>

app/views/layouts/main_page.html.erb
<div id="wrapper">

  <div id="headerwrap">
    <div id="header">
        <% if signed_in? %>
            Signed in as: <%= current_user.email %><%= button_to 'Sign out', sign_out_path, method: :delete %>            
        <% else %>
            <%= link_to 'Sign in', sign_in_path %>
        <% end %>

        <div id="flash">
            <% flash.each do |key, value| %>
                <div class="flash <%= key %>"><%= value %></div>
            <% end %>
        </div>	
    </div>
  </div>

  <div id="navigationwrap">
    <div id="navigation">
      <ul>
  		<li id="li_menu"><a id="menu_Dashboard" href="/dashboard/index">Dashboard</a></li>
  		<li id="li_menu"><a id="menu_Users" href=<%= users_path(@users) %>>Users</a></li>
  		<li id="li_menu"><a id="menu_Timesheets"  href=<%= reports_path(@reports) %>>Timesheets</a></li>
  		<li id="li_menu"><a id="menu_Roles" href=<%= my_roles_path(@roles) %>>Roles</a></li>
  		<li id="li_menu"><a id="menu_Projects" href=<%= projects_path(@projects) %>>Projects</a></li>
  		<li id="li_menu"><a id="menu_Customers" href=<%= customers_path(@customers) %>>Customers</a></li>
  		<li id="li_menu"><a id="menu_Reports" href=<%= dashboard_reports_path %>>Reports</a></li>
	  </ul> 
    </div>
    <%= yield :sub_navigation %>
  </div>

  <div id="contentwrap">
    <div id="content">
      <%= yield :content %>
    </div>
  </div>

</div>

<%= render template: "layouts/application" %>